node1:
  image: ahjdzx/rabbitmq-cluster
  hostname: node1 
  environment:
    - ERLANG_COOKIE=abcdefg
  ports:
    - "5671:5672"
    - "15671:15672"
node2:
  image: ahjdzx/rabbitmq-cluster
  hostname: node2 
  links:
    - node1 
  environment:
    - ERLANG_COOKIE=abcdefg
    - CLUSTER_WITH=node1
    - ENABLE_RAM=true
  ports:
    - "5672:5672"
    - "15672:15672"
node3:
  image: ahjdzx/rabbitmq-cluster
  hostname: node3 
  links:
    - node1 
    - node2 
  environment:
    - ERLANG_COOKIE=abcdefg
    - CLUSTER_WITH=node1
  ports:
    - "5673:5672"
    - "15673:15672"
